/** PC domain error codes — keep in sync with cci-frontend/src/lib/pc/error-catalog.ts */
export enum PcErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  PC_PO_NO_REQUIRED = 'PC_PO_NO_REQUIRED',
  PC_PO_NO_INVALID = 'PC_PO_NO_INVALID',
  PC_PO_NO_TOO_LONG = 'PC_PO_NO_TOO_LONG',
  PC_MFG_DATE_REQUIRED = 'PC_MFG_DATE_REQUIRED',
  PC_MFG_DATE_INVALID = 'PC_MFG_DATE_INVALID',
  PC_MFG_DATE_FUTURE = 'PC_MFG_DATE_FUTURE',
  PC_MATERIAL_REQUIRED = 'PC_MATERIAL_REQUIRED',
  PC_QUANTITY_INVALID = 'PC_QUANTITY_INVALID',
  PC_MATERIAL_NOT_FOUND = 'PC_MATERIAL_NOT_FOUND',
  PC_INSUFFICIENT_STOCK = 'PC_INSUFFICIENT_STOCK',
}
