-- Move audit log tables to logs schema

CREATE SCHEMA IF NOT EXISTS logs;

DO $$
BEGIN
  IF to_regclass('public.api_logs') IS NOT NULL AND to_regclass('logs.api_logs') IS NULL THEN
    ALTER TABLE public.api_logs SET SCHEMA logs;
  END IF;

  IF to_regclass('public.auth_logs') IS NOT NULL AND to_regclass('logs.auth_logs') IS NULL THEN
    ALTER TABLE public.auth_logs SET SCHEMA logs;
  END IF;
END $$;

-- Move likely enum type names generated by TypeORM for auth_logs.action
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'auth_logs_action_enum' AND n.nspname = 'public'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'auth_logs_action_enum' AND n.nspname = 'logs'
  ) THEN
    ALTER TYPE public.auth_logs_action_enum SET SCHEMA logs;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'auth_log_action_enum' AND n.nspname = 'public'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'auth_log_action_enum' AND n.nspname = 'logs'
  ) THEN
    ALTER TYPE public.auth_log_action_enum SET SCHEMA logs;
  END IF;
END $$;

-- Move legacy sequences if they remain in public after table move.
DO $$
BEGIN
  IF to_regclass('public.api_logs_id_seq') IS NOT NULL AND to_regclass('logs.api_logs_id_seq') IS NULL THEN
    ALTER SEQUENCE public.api_logs_id_seq SET SCHEMA logs;
  END IF;

  IF to_regclass('public.auth_logs_id_seq') IS NOT NULL AND to_regclass('logs.auth_logs_id_seq') IS NULL THEN
    ALTER SEQUENCE public.auth_logs_id_seq SET SCHEMA logs;
  END IF;
END $$;
