export enum ErrorCode {
  // Schema Validation Errors
  REQUIRED_FIELD_EMPTY = 'REQUIRED_FIELD_EMPTY',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  NEGATIVE_QUANTITY = 'NEGATIVE_QUANTITY',
  
  // Business Rule Errors
  INVALID_DAY_FOR_MONTH = 'INVALID_DAY_FOR_MONTH',
  TOTAL_MISMATCH = 'TOTAL_MISMATCH',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  
  // System Errors
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  BATCH_ALREADY_EXISTS = 'BATCH_ALREADY_EXISTS',
  INVALID_YEAR_MONTH = 'INVALID_YEAR_MONTH',
}
